### ISSUE TITLE
Hush webpack warnings when blueprint is not installed 

### ISSUE THREAD

**Issue by nomcopter** [nomcopter/react-mosaic#109]
Perhaps switching to `require.resolve` is quieter https://stackoverflow.com/a/15303236

**Comment by iAL-Ahmed** [comment]
@nomcopter Thanks for making this issue. I was just about to make an issue asking if we could either get rid of the webpack warnings or find some way to make blueprint more shakable.

**Comment by nomcopter** [comment]
Hmm.. Nope. That didn't work. Although based on some quick Googling it looks like a pretty common and hard-to-avoid error obnoxiously: https://github.com/webpack/webpack/issues/7713#issuecomment-467888437

**Comment by filipkaniatest** [comment]
Should we have this reopened? The issue persists

**Comment by nomcopter** [comment]
@filipkaniatest I don't think there is anything that can be done in `react-mosaic`. All I could find seemed to suggest that the only way around it seems to be using [`warningsFilter`](https://webpack.js.org/configuration/stats/) in one's webpack config.

**Comment by mejackreed** [comment]
We do it using the webpack ignore plugin: https://github.com/ProjectMirador/mirador/pull/1871

**Comment by gunn4r** [comment]
We tried the webpack ignore plugin but it adds significant overhead to the build time.
