### ISSUE TITLE
Can't load icons for default react mosaic theme

### ISSUE THREAD

**Issue by SukantPal** [nomcopter/react-mosaic#110]
Please check my repository https://github.com/tonkin-game/tonkin-game.github.io. I am not able to get the icons on the window.

Specifically see the `src/index.js` and `src/focus-area-components/ConfigPanel.js` files. The site is live here: https://tonkin-game.github.io/

**Comment by SukantPal** [comment]
I found the issue: my `webpack.config.js` didn't load the CSS properly. The resulting bundle was only containing one the CSS imports - the one that got processed last. I added another CSS file (my own) and all other styles were gone.

I've updated my repository with `MiniCssExtractPlugin`.

**Comment by nomcopter** [comment]
Thanks for closing the loop 👍
