### ISSUE TITLE
MosaicWithoutDragDropContext with MosaicWindow do not work.

### ISSUE THREAD

**Issue by YahngSungho** [nomcopter/react-mosaic#112]
### Bug report

- __Package version(s)__: ^2.1.0
- __Browser and OS versions__: chrome latest

After several experiments:

`Mosaic` & `MosaicWindow` => work

`MosaicWithoutDragDropContext` => works

`MosaicWithoutDragDropContext` & `MosaicWindow` => fail

`MosaicWithoutDragDropContext` & `MosaicWindow` & `DragDropContext(HTML5Backend)(MosaicWithoutDragDropContext` & `MosaicWindow )` => also fail

Can not `MosaicWithoutDragDropContext` work with `MosaicWindow`? Or are there other way to use?

#### Steps to reproduce
```
class MosaicTest extends Component {
  render () {
    const TITLE_MAP = {
      a: 'Left Window',
      b: 'Top Right Window',
      c: 'Bottom Right Window',
      new: 'New Window'
    }
    return (
        <MosaicWithoutDragDropContext
          renderTile={(id, path) => (
            <MosaicWindow path={path} createNode={() => 'new'} title={TITLE_MAP[id]}>
              {TITLE_MAP[id]}
            </MosaicWindow>
          )}
          initialValue={{
            direction: 'row',
            first: 'a',
            second: {
              direction: 'column',
              first: 'b',
              second: 'c'
            }
          }}
        />
    )
  }
}

const MosaicTestWrapper = DragDropContext(HTML5Backend)(MosaicTest)
```

**Comment by nomcopter** [comment]
Does your version of `react-dnd-html5-backend` match with the one included in` react-mosaic`?

**Comment by YahngSungho** [comment]
@nomcopter 
Thank you for your reply. And yes, this is in my `package.json`

```
    "react-dnd": "^5.0.0",
    "react-dnd-html5-backend": "^5.0.1",
```

**Comment by YahngSungho** [comment]
@nomcopter 
To express behavior more precisely: If I put MosaicWindow in a tile, it seems to be omitted. For example, 'foo' and 'MosaicWindow' in the tile will only show 'foo'. Also, Only 'foo' is visible in the dev tool. What's even stranger is that no error message is displayed.

**Comment by YahngSungho** [comment]
@nomcopter 
So far I've done some more experiments, but all failed. But when I created a new project and tried that code, it worked. Maybe it is due to some environmental differences that I do not know. But I have no idea what it is. 

So I made it test repo.

https://github.com/YahngSungho/dfsfdsfsfdsfwfsd/tree/helpForReactMosaic

I created 'helpForReactMosaic' branch. There I cleaned all the code except for trying react-mosaic, so you can play with it without distraction. You could run 'npm start' there.

**Comment by 4ian** [comment]
FYI, I have the same issue when upgrading my dependencies here:
https://github.com/4ian/GDevelop/pull/1119/files

I'm using `MosaicWithoutDragDropContext` with `MosaicWindow` and have no rendering of the window at all.
But using version 3.1.0 of react-mosaic along with:
```    
    "react-dnd": "^5.0.0",
    "react-dnd-html5-backend": "^5.0.1",
```

seems to get things back working :) (unfortunately can't use this, because this version of react-dnd is too old for other dependencies - ideally would be great if we could use latest versions of react-dnd)

**Comment by nomcopter** [comment]
I tried upgrading to the latest version of `react-dnd` but ran into a couple issues:
 - This would require a fair amount of build system to work to keep `react-mosaic` ES5 compatible as now they publish ES6
- I ran into a lot of issues just getting dragging and dropping working at all in the ExampleApp..

`react-dnd` releases breaking versions shockingly frequently - but agreed - `react-mosaic` needs to upgrade (accepting PRs!)

**Comment by 4ian** [comment]
Thanks for the update :) Sad to know that there are breaking changes to be taken care of before upgrading - at least for now it still seems that ensuring the exact same versions of react-dnd will get things working.
