### ISSUE TITLE
Blank page in Edge

### ISSUE THREAD

**Issue by phyper** [nomcopter/react-mosaic#121]
### Bug report

- __Package version(s)__:  
react-mosaic v3.2.0
react v16.9.0

- __Browser and OS versions__: Edge (latest)

#### Steps to reproduce

If I have the following line in my code
**import { Mosaic } from 'react-mosaic-component';**
I get a blank space in Edge even if I don't use Mosaic in render at all.
After I remove that line, the app renders normally.

However, v2.0.2 works correctly.

#### Actual behavior

The page is blank and the react app has not rendered at all.
In a console, there's the following error
**SCRIPT1028: SCRIPT1028: Expected identifier, string or number vendors~app.xyz.bundle.js**

#### Expected behavior
The app renders and the screen is not white

**Comment by nomcopter** [comment]
Thanks for the report! Will dig into along with #118

**Comment by nomcopter** [comment]
<img width="1680" alt="Screen Shot 2019-09-22 at 10 27 22 PM" src="https://user-images.githubusercontent.com/1079273/65403380-38d0a780-dd88-11e9-8a23-6c274febba82.png">
Works fine for me in Edge - looks like a problem with your bundler.
