### ISSUE TITLE
Drag-to-create windows

### ISSUE THREAD

**Issue by t3db0t** [nomcopter/react-mosaic#122]
How would we accomplish drag-to-create, say using Blueprint's own [Tree](https://blueprintjs.com/docs/#core/components/tree)? I.e. click on an item in the tree and drag into the windowed area to create a new window.

I can't tell from looking at the current API how this would be accomplished...

**Comment by nomcopter** [comment]
Thanks - glad it's working well for you. It should be possible by creating your own [`DragSource`](https://react-dnd.github.io/react-dnd/docs/api/drag-source) that uses `MosaicDragType.WINDOW`. Then, if you implement `endDrag` in a [similar fashion to `MosaicWindow`](https://github.com/nomcopter/react-mosaic/blob/c19c6b4f574b8c20492ca46906947fe82bbdcdbd/src/MosaicWindow.tsx#L275), you should be able to create a new window.

Let me know if that doesn't work for you.

**Comment by t3db0t** [comment]
Thanks so much, I will take a stab at this!
