### ISSUE TITLE
Styles not imported?

### ISSUE THREAD

**Issue by t3db0t** [nomcopter/react-mosaic#123]
### Bug report

Implementing the basic example but no themes are imported. 

#### Steps to reproduce

1. Use example code (i.e. Examples/Simple Tiling) from README

Yes, I have installed Blueprintjs and am importing those stylesheets.

#### Actual behavior

Get this: 
![Screen Shot 2019-10-17 at 3 33 41 PM](https://user-images.githubusercontent.com/203307/67041466-b8d1ff00-f0f3-11e9-8808-970c25e31e61.png)

#### Expected behavior

Get styled windows

**Comment by nomcopter** [comment]
Example repo or CodePen?

**Comment by t3db0t** [comment]
Nevermind—I was doing this way wrong. X-)
