### ISSUE TITLE
Outdated react-dnd (v7.7.0) throws error in the latest stable TypeScript (3.7)

### ISSUE THREAD

**Issue by bitjson** [nomcopter/react-mosaic#130]
### Bug report

- __Package version(s)__: v3.2.0
- __Browser and OS versions__: all

#### Steps to reproduce

1. Install react-mosaic in a project using the latest version of TypeScript
1. Try to build

#### Actual behavior

An error is thrown by the compiler:
```
/[project]/node_modules/dnd-core/lib/cjs/interfaces.d.ts
TypeScript error in /[project]/node_modules/dnd-core/lib/cjs/interfaces.d.ts(1,10):
Import declaration conflicts with local declaration of 'Unsubscribe'.  TS2440

  > 1 | import { Unsubscribe } from 'redux';
      |          ^
    2 | export declare type Identifier = string | symbol;
    3 | export declare type SourceType = Identifier;
    4 | export declare type TargetType = Identifier | Identifier[];
```

#### Expected behavior

Successful build

---

Anyone know of a workaround that can be used until `react-mosaic` is updated to a newer version of `react-dnd`? (See also: [`react-dnd` issue](https://github.com/react-dnd/react-dnd/issues/1560#issuecomment-550584681).)

**Comment by nomcopter** [comment]
Will try to get to this. Accepting PRs in the meantime.
