### ISSUE TITLE
Question on MosaicNode format

### ISSUE THREAD

**Issue by Artur93gev** [nomcopter/react-mosaic#131]
Hi. Thanks for this great package.
Sorry for not being according to the template provided(I have a question).

Is there a way to convert the *MosaicNode* to corresponding `(x, y, width, height)` and also the reverse convert?

**Comment by Artur93gev** [comment]
Example.
```
{
        direction: 'row',
        first: 'a',
        second: 'b',
        splitPercentage: 40,
}
```
I want it to become.
```
[{
   x: 0,
   y: 0,
   width: 100,
   height: 40,
},
{
   x: 0,
   y: 40,
   width: 100,
   height: 60,
}
]
```
NOTE:: all the values are in percents

**Comment by nomcopter** [comment]
That's essentially what mosaic does for you to natively: https://github.com/nomcopter/react-mosaic/blob/master/src/MosaicRoot.tsx#L31

So, definitely possible, but ideally something you shouldn't need.
