### ISSUE TITLE
Popagate custom drag handle via css class name?

### ISSUE THREAD

**Issue by charbugs** [nomcopter/react-mosaic#132]
Hello,

Is there a way to propagate a custom drag handle via css class name?

I have a third-party window component that already has a toolbar and I want to make this toolbar draggable. I can't -- or rather don't want to -- access the internals of that window component, so there is no way to get ahold of that toolbar element and make it draggable via `connectDragSource`. But I know the class name of that element. Is there a way to accomplish that using the class name?

Thank you!

**Comment by nomcopter** [comment]
react-mosaic uses react-dnd under the hood. So if it can be done with react-dnd then yes! I expect doing it imperatively will be rather tough though.
