### ISSUE TITLE
Strict mode support

### ISSUE THREAD

**Issue by gempir** [nomcopter/react-mosaic#152]
It would be nice if react-mosaic supported React strict mode without warnings. `findDOMNode` is deprecated in strict mode and should be replaced with a reference.

> Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Blueprint3.ResizeSensor which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://fb.me/react-strict-mode-find-node

![image](https://user-images.githubusercontent.com/9765622/97102190-d2f9d200-16a3-11eb-9ee9-f5bd64f21474.png)

![image](https://user-images.githubusercontent.com/9765622/97102261-4e5b8380-16a4-11eb-93fc-477f089854fb.png)

- __Package version(s)__: 4.1.1
- __Browser and OS versions__: Ubuntu 20.04 Chrome 85

#### Steps to reproduce

1. Use Strict Mode https://reactjs.org/docs/strict-mode.html
2. Add a new split 
3. Check the console

**Comment by nomcopter** [comment]
This looks like a bug on Blueprint 3. There are no usages of `findDomNode` in react-mosaic and Blueprint is an optional dependency.
