### ISSUE TITLE
DndProvider breaking the app on latest versions

### ISSUE THREAD

**Issue by aaliakseyenka** [nomcopter/react-mosaic#175]
### Bug report

- __Package version(s)__: 5.0.0
- __Browser and OS versions__: MacOS, all browsers

#### Steps to reproduce

1. npm i react-mosaic-component
1. create app with basic setup: https://github.com/nomcopter/react-mosaic#apptsx

#### Actual behavior
App is failed to start wit error:

```Could not find the drag and drop manager in the context of DragSource(InternalMosaicWindow). Make sure to render a DndProvider component in your top-level component. Read more: http://react-dnd.github.io/react-dnd/docs/troubleshooting#could-not-find-the-drag-and-drop-manager-in-the-context```

#### Expected behavior
works like a magic.

Notes:
1. everything works with yarn.
2. if explicitly wrap `Mosaic` with `<DndProvider backend={HTML5Backend}>` in own app, everything works as expected.

**Comment by bigloong** [comment]
any other soluation?

**Comment by Wozniaxos** [comment]
Occured same problem, do you have any update on this? In my case wrapping Mosaic with Dnd won't help

**Comment by Wozniaxos** [comment]
Ok, It seems that the problem relies on that yarn has different behavior than npm 7+ and does not install peerDependencies automatically. When I've installed it with the newest npm but with --legacy-peer-deps everything works fine.

**Comment by nomcopter** [comment]
Hmm - this is obnoxiously npm 7+ installing peer dependencies and so that there are multiple versions of `react-dnd` in the path. Then their contexts don't talk. I'll try to think of a fix but for now installing with `npm install --legacy-peer-deps` or `yarn` fixes this issue.

**Comment by nomcopter** [comment]
Fixed in https://github.com/nomcopter/react-mosaic/releases/tag/v5.2.2
