### ISSUE TITLE
Heading levels should only increase by one

### ISSUE THREAD

**Issue by Shane79717** [nomcopter/react-mosaic#178]
Hello,

We are currently experiencing an accessibility issue that has been reported back by Axe. According to the report, it indicates that the header levels should only increase by one, highlighting an `<h4>` tag as the area for further analysis. Looking through our code base along with the dependency itself, the problem seems to be around the heading: "No Windows Present". Is there a possibility that this element could be changed to something else? Or alternatively, do you have any suggestions on how to resolve it?

**Issue Description**
Ensures the order of headings is semantically correct

**Element location**
h4

**Element source**
`<h4>Main</h4>
`
**To solve this issue, you need to...**
Fix the following:
Heading order invalid

**Comment by nomcopter** [comment]
The `zeroStateView` prop of `Mosaic` let's you customize this view in order to change what is rendered there.

**Comment by Shane79717** [comment]
> The `zeroStateView` prop of `Mosaic` let's you customize this view in order to change what is rendered there.

I managed to find a resolution to our problem using the prop you mentioned above. Thanks for the feedback.
