### ISSUE TITLE
Feature Request: register callback to additionalControls

### ISSUE THREAD

**Issue by jack-tutor** [nomcopter/react-mosaic#180]
I want to cache in local storage whether or not the additionalControls are open.  This is so if the page is refreshed, the additional controls remain open or closed as they were before.

To do this, I either need to implement my own additionalControls button (and disable the existing button) OR have some type of useChange callback that responds to the change of additionalControls (this is what I would prefer).  I suppose a simple getter for this state would somewhat work, that would be better than nothing.

Then on reload of the site, I could use the provided setAdditionalControlsOpen function to set the desired additional controls state.

I can imagine lots of other use cases for a callback on the additionalControls.

**Comment by nomcopter** [comment]
Implemented in v5.2.0
