### ISSUE TITLE
React mosaic 5.0 with Blueprintjs 4.0 has window buttons that are too big

### ISSUE THREAD

**Issue by casperOne** [nomcopter/react-mosaic#181]
### Bug report

- __Package version(s)__: 5.0.0
- __Browser and OS versions__: Chrome 99, Windows 11

#### Steps to reproduce

When using react-mosaic version 5.0.0 with @blueprintjs/core 4.0.0, the buttons seem to be too big for the toolbarL

![image](https://user-images.githubusercontent.com/561862/160033240-57b6cbe1-38b3-4948-ab77-f5853dad6674.png)

#### Actual behavior

You can see it reproduced in the codesandbox here:

https://codesandbox.io/s/react-mosaic-blueprint-4-cxfdvg

#### Notes

The behavior only exhibits itself if blueprintjs *and* react-mosaic are at the versions above; if blueprint js is at version 3.54.0 or react-mosaic is at version 4.1.1 the height of the buttons fits the toolbar.

Looking at the rendered output, it seems like the buttons are using the `bp3` prefix:

![image](https://user-images.githubusercontent.com/561862/160035580-e3321f12-7f4a-45eb-aece-ac18b2a8bfb2.png)

Even though `bp4` is the recommendation for blueprint version 4:

https://blueprintjs.com/docs/#core/classes.namespacing

I'm not sure if there's a way to do this already in the project, but it seems that it needs to be "aware" of blueprint 4.

When changing the prefixes (through the browser) to bp4, the buttons seem to be properly proportioned.

**Comment by casperOne** [comment]
I've submitted a PR, if @nomcopter or another maintainer would approve, I believe this would do the trick.

**Comment by casperOne** [comment]
Confirmed the new build addresses the issue, thanks @nomcopter !

**Comment by nomcopter** [comment]
Fantastic!
