### ISSUE TITLE
Not compatible with @types/react 18

### ISSUE THREAD

**Issue by tran-simon** [nomcopter/react-mosaic#184]
With version 18 of @types/react, [the children prop has been removed from Component](https://solverfox.dev/writing/no-implicit-children/).

MosaicWindow cannot be used if using version 18 of @types/react.

For now, I'm using this workaround:
```
import { Mosaic, MosaicWindow } from 'react-mosaic-component';

declare module 'react-mosaic-component' {
  //@ts-ignore
  export interface MosaicWindowProps<T extends MosaicKey> {
    children: React.ReactNode;
  }
}
```

**Comment by nomcopter** [comment]
Fixed in v5.2.0
