### ISSUE TITLE
The icons of the header of each window disappeared after upgrade the @blueprintjs packages

### ISSUE THREAD

**Issue by rislam169** [nomcopter/react-mosaic#187]
### Bug report

- __Package version(s)__: @blueprintjs/core 4.4.1 and @blueprintjs/icons 4.3.0 (both are latest)
- __Browser and OS versions__: In all OS versions and Browser versions are facing same issue

#### Steps to reproduce

Please follow [Code Sandbox](https://codesandbox.io/s/react-mosaic-button-icon-ldz84b)

#### Actual behavior

The readme of the react-mosaic-component package states, that it can be used with the latest version of the @blueprintjs packages in order to provide a default theme, including icons for the header of each window (see [examples in the readme file](https://github.com/nomcopter/react-mosaic#blueprint-theme)). However, when we have upgraded the @blueprintjs packages, the icons disappeared from the window headers

#### Expected behavior

The icons for the header of each window should visible properly.

**Comment by nomcopter** [comment]
You just need to set `blueprintNamespace="bp4"` in the root Mosaic's props.
