### ISSUE TITLE
SolidJs Support

### ISSUE THREAD

**Issue by coolRoger** [nomcopter/react-mosaic#194]
Thank you for this great component. 
Our app is moving forward to SolidJs Framework. We still want to use this component in our app, so do you have any suggestion or workaround to make this component works in SolidJs?

**Comment by nomcopter** [comment]
Something like https://github.com/Sawtaytoes/reactjs-solidjs-bridge may be able to help you. This component is based on React though and has no plans to support any other UI frameworks natively.
