### ISSUE TITLE
Outdated Dependencies

### ISSUE THREAD

**Issue by christoph-pflueger** [nomcopter/react-mosaic#195]
Some of the dependencies are quite outdated. As far as I see, the dependencies haven't changed a lot but contain significant improvements (ESM support, Node 18 support, React 18 support, ...) and fix a couple of errors currently shown to us.

It'd be great if you couple update the dependencies for us, especially `react-dnd`, `react-dnd-html5-backend`, `react-dnd-multi-backend`, `react-dnd-touch-backend` and `uuid`.

Let me know if you need any help. I'm willing to help out.

**Comment by greggman** [comment]
Fork it, fix it, then submit a PR?

**Comment by git-chrisp** [comment]
> Fork it, fix it, then submit a PR?

You must be mad thinking I'll spend just one minute on a dead repository without as much as a reply in almost a month.

**Comment by greggman** [comment]
@git-chrisp did you find a good alternative?

**Comment by nomcopter** [comment]
I was hoping to have time to bump it myself but didn't end up able to - would be able to get a PR in pretty quickly though.

**Comment by jtbandes** [comment]
I've made a PR, but will need some help with testing: https://github.com/nomcopter/react-mosaic/pull/201
