### ISSUE TITLE
Add touch device support

### ISSUE THREAD

**Issue by aldensc** [nomcopter/react-mosaic#41]
Looking for window dragging that is also supported for touch devices.  Looks like react-dnd does not support it out of the box, but react-dnd-touch-backend could provide this support.

**Comment by nomcopter** [comment]
Mosaic exports `MosaicWithoutDragDropContext` so you could wrap that with `react-dnd-touch-backend` which should mostly work for you (I haven't tested it). There is still some open work within Mosaic to make it support the drag preview.
